Improve GitHub action
typeddjango/awesome-python-typing pull request #45
Opened 2020-10-01 20:28 UTC by DmytroLitvinov

@sobolevn , improve GitHub action to also run CI on push to `master`. It will allow us to add badge for `master` branch in future.

2020-10-01 20:31 UTC, sobolevn requested changes
Thanks! 

Also see https://github.com/typeddjango/awesome-python-typing/pull/44#issuecomment-702379835

2020-10-01 20:31 UTC, sobolevn commented on .github/workflows/linter.yml
> +name: linter
Let's keep the name unedited.

Because, we will have empty sections in the Actions dashboard otherwise.

2020-10-01 20:36 UTC, DmytroLitvinov commented
@sobolevn, done :+1:

2020-10-01 22:16 UTC, sobolevn commented on README.md
> +# Awesome Python Typing [![Awesome](https://awesome.re/badge-flat2.svg)](https://awesome.re) [![Gitter](https://img.shields.io/gitter/room/mypy-django/Lobby?color=9cf&style=flat-square)][TypedDjango]
We store our build badge in `contributing.md`

2020-10-02 19:24 UTC, sobolevn approved these changes

2020-10-02 19:24 UTC, merged

2020-10-02 19:24 UTC, sobolevn commented
Thanks!